### ISSUE TITLE
[Bug report] Couldn't resolve the package 'flutter_image_compress' in 'package:flutter_image_compress/flutter_image_compress.dart'.

### ISSUE THREAD

**Issue by SittiphanSittisak** [fluttercandies/flutter_image_compress#239]
### Version

1.1.3

### Platforms

Web

### Device Model

chorme driver

### flutter info

```sh
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.19045.2728], locale th-TH)
[√] Windows Version (Installed version of Windows is version 10 or higher)                       
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web                                                
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.5)   
[√] Android Studio (version 2022.1)                                             
[√] IntelliJ IDEA Community Edition (version 2022.2)                            
[√] VS Code (version 1.76.2)                                                    
[√] Connected device (3 available)                                              
[√] HTTP Host Availability                                                      
                                                                                
• No issues found!
```

### How to reproduce?

I just going to use this package.
After adding `flutter_image_compress: ^1.1.3` in the `pubspec.yaml` and trying to use this package by importing `import 'package:flutter_image_compress/flutter_image_compress.dart';`, I got this error. (just add this import 'package:...')

### Logs

```sh
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
Error: Couldn't resolve the package 'flutter_image_compress' in 'package:flutter_image_compress/flutter_image_compress.dart'.
../project/lib/test.dart:8:8: Error: Not found: 'package:flutter_image_compress/flutter_image_compress.dart'
import 'package:flutter_image_compress/flutter_image_compress.dart';
       ^
../project/lib/test.dart:71:26: Error: Undefined name 'FlutterImageCompress'.
      var result = await FlutterImageCompress.compressWithList(
                         ^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
Null check operator used on a null value
#0      IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:224:69)
#1      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:721:46)
<asynchronous suspension>
#2      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:614:9)
<asynchronous suspension>
#3      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1222:11)
<asynchronous suspension>
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.
```

### Example code (optional)

```Dart
import 'package:flutter_image_compress/flutter_image_compress.dart';
```

**Comment by CaiJingLong** [comment]
Now does not support web.

**Comment by SittiphanSittisak** [comment]
aww, is this possible to add it in the new feature?

**Comment by CaiJingLong** [comment]
Use new version 2.0.1
